### ISSUE TITLE
create_models() exits entire program if no tables are found

### ISSUE THREAD

**Issue by dargueta** [xnuinside/omymodels#22]
**Describe the bug**

If create_models() doesn't find tables in the DDL string it's given, it exits the program.

**To Reproduce**

In an interpreter (IDLE, IPython, etc.) run `create_models()` with a string containing only whitespace. The interpreter exits.

**Expected behavior**

If this function is to be used in a library, ideally an exception would be thrown with information about the error. The issue is [here](https://github.com/xnuinside/omymodels/blob/main/omymodels/common.py#L49); I'd greatly appreciate it if you could throw, say, a `ValueError` or something instead of exiting.

Personally, when I'm making a library, I like creating my own error hierarchy (e.g. [here](https://github.com/dargueta/binobj/blob/master/binobj/errors.py)) so the source of the exception is very clear to the caller, and they can selectively catch certain errors. For example, here I would create two exceptions:

```py
# omymodels/errors.py

class Error(Exception):
    """Base class for most if not all errors thrown by this library""

class NoTablesFoundError(Error):
    """No tables were found in the DDL string."""
```

Then instead of `sys.exit()` I would throw `NoTablesFoundError`. This design allows me to add new exceptions as I see fit, and standardize error messages (example [here](https://github.com/dargueta/binobj/blob/master/binobj/errors.py#L256-L273)).

These are my personal design habits, don't let me dictate yours!

**Additional context**

Python: 3.8.2
Version: 0.8.3

**Comment by xnuinside** [comment]
@dargueta interesting, I will try reproduce it on the evening and fix it. About errors - I'm doing it similar ways usually. In this library I just had not time to came yet to handle exceptions proper way  :)

**Comment by xnuinside** [comment]
@dargueta released in 0.8.4 https://pypi.org/project/omymodels/  tests: https://github.com/xnuinside/omymodels/blob/main/tests/test_omymodels.py#L12

**Comment by dargueta** [comment]
Thanks! Sorry I'm being such a pain with all these tickets. 😅

**Comment by xnuinside** [comment]
@dargueta no :) I’m glad that package can be useful somehow, if will be any suggestions or issues feel free to open new tickets!
