### ISSUE TITLE
Any way of keeping the exsisting column names as they are?

### ISSUE THREAD

**Issue by avisual** [xnuinside/omymodels#36]
When using dll with capitals in the name for dataclasses anything with capitals gets renamed such as NHS become n_h_s in the dataclass. is there any way of creating the fieldname as they are in the dll?

GBMSM smallint  becomes  g_b_m_s_m: int = None

**Comment by avisual** [comment]
Also I am seeing the column name order being re-arranged as in the order changes when output to dataclass

**Comment by xnuinside** [comment]
@avisual I can implement it as a some setting in create_models() method, something like argument 'no_auto_snake_case=True' - to remove auto formatting to snake case that I use in library

do you think it should be related only to attributes (properties) of classes or also to class names?

**Comment by avisual** [comment]
if you are generating from existing tables keeping the names the same as originals really helps. I know that the purest of coders would say that fails naming conventions. but then we all work in legacy systems or have no control over some data

**Comment by xnuinside** [comment]
@avisual I mean if your table called like 'products' with small case. You want as a result generate `class products():` - also in the code? or capitalize it?

**Comment by xnuinside** [comment]
arg `no_auto_snake_case=True` was added in version 0.12.0, version already released - https://pypi.org/project/omymodels/

@avisual can you show the sample with columns re-arrange?  as input sample - output sample?

**Comment by xnuinside** [comment]
I will close issue as a stale. If it will be still actual - pls open it again

**Comment by avisual** [comment]
Sorry had been away on holiday, will try this out today thank you for fixing :)

**Comment by faccini-bs** [comment]
We could add this option as a flag for the cli e.g. "--auto-snake" set to false by default
just wanted to put this here to remind myself
