### ISSUE TITLE
Simple Online App

### ISSUE THREAD

**Issue by archongum** [xnuinside/omymodels#52]
Simple Online App 😀

https://archon-omymodels-online.hf.space

![image](https://github.com/xnuinside/omymodels/assets/20929338/51ee3d60-33e7-4d4d-bb39-04c00b1f3154)

**Comment by xnuinside** [comment]
wow ) it is amazing, thank you! I will add link to the documentation

**Comment by xnuinside** [comment]
@archongum I added appreciation for you in Readme & link to the web ui :) thank you one more time
