### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by archongum** [xnuinside/omymodels#53]
**Describe the bug**
DOES NOT work in Python `3.11` because of using `py-models-parser` according to  https://github.com/xnuinside/py-models-parser/issues/10

**To Reproduce**
Run in Python 3.11

**Expected behavior**
Support Python 3.11

**Screenshots**
![image](https://github.com/xnuinside/omymodels/assets/20929338/df98d369-4298-4ba1-8e9d-b5e7720bdac3)

**Comment by xnuinside** [comment]
thanks for opening the issue, will work on new release right now, support for python3.11 added to https://github.com/xnuinside/py-models-parser
