### ISSUE TITLE
Typo in types.py

### ISSUE THREAD

**Issue by umaxfun** [xnuinside/omymodels#59]
```
ddl = """
CREATE TABLE qwe (
    id integer NOT NULL,
    name character varying(255),
);
"""
result = create_models(ddl, models_type='sqlmodel')['code']
```

This code fails due to the typo in https://github.com/xnuinside/omymodels/blob/4893e38f07472c3553736c1947144004cbaf38c8/omymodels/types.py#L11

When `character_vying` changed to `character varying` everything seems to work.

**Comment by xnuinside** [comment]
@umaxfun hi! thanks for opening the issue, fix released in 0.17.0 version - https://github.com/xnuinside/omymodels/blob/main/tests/functional/generator/test_sqlmodel.py#L364 (test)
